<script lang="ts">
  import { onMount } from 'svelte';
  import AttachmentList from '../../src/lib/components/AttachmentList.svelte';
  import Markdown from '../../src/lib/components/Markdown.svelte';
  let attachments = $state<{ id: string; name: string; mimeType: string; size: number; path: string; previewDataUrl: string }[]>([]);
  let markdown = $state('Waiting for tool screenshot…');
  onMount(() => {
    const canvas = document.createElement('canvas');
    canvas.width = 1600; canvas.height = 960;
    canvas.getContext('2d')?.fillRect(0, 0, canvas.width, canvas.height);
    const screenshot = canvas.toDataURL('image/png');
    const pixel = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=';
    attachments = [
      { id: 'screen', name: 'Screenshot.png', mimeType: 'image/png', size: 68, path: 'Generated by Codex', previewDataUrl: screenshot },
      { id: 'pixel', name: 'Pixel.png', mimeType: 'image/png', size: 68, path: 'Generated by Codex', previewDataUrl: pixel },
    ];
    markdown = `![Tool screenshot](${screenshot})`;
  });
</script>

<main><AttachmentList {attachments}/><Markdown text={markdown}/></main>
<style>main{padding:20px;--line:#ddd;--panel:#fff;--paper:#fff;--soft:#eef8f8;--ink:#171717;--muted:#667;--accent:#066;--accent-ink:#044;--interface-font-ratio:1;--interface-font:system-ui;--mono:ui-monospace}</style>
