<script lang="ts">
 import {ArchiveRestore,Search,Trash2} from '@lucide/svelte'; import Modal from './Modal.svelte'; import type {Snapshot,Task} from '$lib/types';
 type Preview={supported:boolean;reason:string;files:string[]};
 let {snapshot,open=false,onclose,onRestore,onDelete,previewDeletion}:{snapshot:Snapshot;open?:boolean;onclose:()=>void;onRestore:(id:string)=>void|Promise<void>;onDelete:(task:Task,removeNative:boolean)=>void|Promise<void>;previewDeletion:(id:string)=>Promise<Preview>}=$props();
 let query=$state(''),pending=$state<Task|null>(null),preview=$state<Preview|null>(null),previewLoading=$state(false),removeNative=$state(false),busy=$state(false),error=$state(''),generation=0;
 // Retaining the modal for its exit must not retain a destructive confirmation on reopening.
 $effect(()=>{if(open){query='';pending=null;preview=null;previewLoading=false;removeNative=false;error='';}});
 // Internal agents and their tasks never appear in the archived chats list, even if the snapshot contains them.
 const internalAgentIds=$derived(new Set(snapshot.agents.filter(agent=>agent.internal===true).map(agent=>agent.id)));
 const rows=$derived(snapshot.tasks.filter(t=>t.archived&&!internalAgentIds.has(t.agentId)).filter(t=>{const a=snapshot.agents.find(a=>a.id===t.agentId)?.name??'',h=snapshot.hosts.find(h=>h.id===t.hostId)?.name??'';return [t.title,a,h].join(' ').toLowerCase().includes(query.toLowerCase())}).toSorted((a,b)=>b.updatedAt-a.updatedAt));
 async function confirm(task:Task){pending=task;preview=null;removeNative=false;error='';const g=++generation;previewLoading=true;try{const value=await previewDeletion(task.id);if(g===generation)preview=value}catch(reason){if(g===generation)preview={supported:false,reason:reason instanceof Error?reason.message:String(reason),files:[]}}finally{if(g===generation)previewLoading=false}}
 async function restore(id:string){busy=true;error='';try{await onRestore(id)}catch(reason){error=reason instanceof Error?reason.message:String(reason)}finally{busy=false}}
 async function remove(){if(!pending)return;busy=true;error='';try{await onDelete(pending,!!preview?.supported&&removeNative);pending=null}catch(reason){error=reason instanceof Error?reason.message:String(reason)}finally{busy=false}}
</script>
<Modal title={pending?'Permanently delete archived chat':'Archived chats'} {open} onclose={()=>{if(!busy){generation++;onclose()}}}>
 {#if !pending}<label class="search"><Search size={14}/><input data-autofocus aria-label="Search archived chats" bind:value={query} placeholder="Search chat, agent, or host"/></label>{#if error}<p class="error">{error}</p>{/if}{#each rows as task}<article><span><b>{task.title}</b><small>{snapshot.agents.find(a=>a.id===task.agentId)?.name??'Unknown agent'} · {task.provider} · {snapshot.hosts.find(h=>h.id===task.hostId)?.name??'Unknown host'}</small></span><div><button class="secondary" disabled={busy} onclick={()=>restore(task.id)}><ArchiveRestore size={14}/>Restore</button><button class="icon danger" aria-label={`Permanently delete ${task.title}`} onclick={()=>confirm(task)}><Trash2 size={14}/></button></div></article>{:else}<p class="empty">No archived chats match this search.</p>{/each}
 {:else}<h3>Delete “{pending.title}”?</h3><p>{pending.provider} · {snapshot.hosts.find(h=>h.id===pending?.hostId)?.name??'Unknown host'}</p>{#if pending.nativeSessionId}<code>{pending.nativeSessionId}</code>{/if}<p>This removes the saved Monitter chat and transcript.</p>{#if previewLoading}<p>Checking native session files…</p>{:else if preview?.supported}<label class="switch"><input type="checkbox" role="switch" bind:checked={removeNative}/>Also remove native session files from disk</label>{#if removeNative}<ul>{#each preview.files as file}<li><code>{file}</code></li>{/each}</ul>{/if}{:else}<p class="hint">Native session files will be kept: {preview?.reason||'No safe cleanup is available.'}</p>{/if}{#if error}<p class="error">{error}</p>{/if}<footer><button class="secondary" disabled={busy} onclick={()=>{generation++;pending=null;error=''}}>Cancel</button><button class="danger" disabled={busy} onclick={remove}><Trash2 size={14}/>Delete permanently</button></footer>{/if}
</Modal>
<style>.search,article,article div,footer{display:flex;gap:8px;align-items:center}.search{padding:7px;border:1px solid var(--line);border-radius:7px}.search input{border:0;flex:1;min-width:0;color:var(--ink);background:transparent}article{justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line)}article span{display:grid;min-width:0}small,.hint{color:var(--muted);font-size:calc(11px * var(--interface-font-ratio, 1))}article b,article small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}article>div{flex:none}code{overflow-wrap:anywhere;font-size:calc(11px * var(--interface-font-ratio, 1))}.secondary,.danger{display:inline-flex;gap:6px;align-items:center;padding:8px;border-radius:6px}.secondary:hover,.danger:hover{background:var(--soft)}footer{justify-content:flex-end}.danger,.error{color:var(--danger,#b54a55)}.switch{display:flex;align-items:center;gap:10px;font-size:calc(12px * var(--interface-font-ratio, 1));cursor:pointer}.switch input{appearance:none;position:relative;flex:none;width:30px;height:18px;border:0;border-radius:20px;background:var(--line);cursor:pointer;transition:background .15s}.switch input::after{content:'';position:absolute;left:3px;top:3px;width:12px;height:12px;border-radius:50%;background:var(--panel);box-shadow:0 1px 3px #0003;transition:transform .15s}.switch input:checked{background:var(--accent)}.switch input:checked::after{transform:translateX(12px)}.empty{color:var(--muted);padding:20px;text-align:center}</style>
